### ISSUE TITLE
Submit file doesn't take a tuple

### ISSUE THREAD

**Issue by GShepherdTC** [joesecurity/joesandboxcloudapi#6]
I see in the comments, it says:
        Parameters:
          sample:       The sample to submit. Needs to be a file-like object or a tuple in
                        the shape (filename, file-like-object).

Which I tried and I believe correctly.   And I get:
          TypeError: a bytes-like object is required, not 'tuple'

It works great if I just pass a file-like-object but of course that doesn't allow me to specify a file name. They all come in as 'sample' which I believe is because of line 179:
        files = {'sample': sample}

Thanks. Greg.

**Comment by serpulga** [comment]
+1

**Comment by joesecurity** [comment]
Thanks for reporting this issue. Fixed in version 2.6.1 which is currently uploading.

https://github.com/joesecurity/joesandboxcloudapi/commit/b25a8196ec101218c6ae03d8c90dc061cca38f25
