### ISSUE TITLE
Undocumented status "finishedrun"

### ISSUE THREAD

**Issue by serpulga** [joesecurity/joesandboxcloudapi#7]
From the endpoint **`/v2/analysis/info`** we are getting an unexpected value for the `status` attribute:

```javascript
{"status": "finishedrun", "runs": [ ... ], ... }
```

This value isn't documented so we are wondering about its meaning.

[Doc Link](https://jbxcloud-oem1.joesecurity.org/userguide?sphinxurl=usage/webapi.html#v2-analysis-info)
```
"The status field is one of submitted, running, finished. ...    "
```

Thank you.

**Comment by joesecurity** [comment]
Thanks for the bug report. You're indeed seeing an internal status which we will hide in a future version. You can treat it the same as `running`.

This status appears between multiple runs. In case an analysis contains 2 runs, the state changes as follows:

1. submitted
2. running
3. finishedrun       (we will hide this in the future)
4. running
5. finished

**Comment by joesecurity** [comment]
We updated our servers so you should not encounter this status anymore.
